import { MetaHeroes } from "../types";

export const PREFIX = "!";

export const categoryAliases: { [key: string]: keyof MetaHeroes } = {
	hc: "Carry",
	mid: "Mid",
	off: "Off",
};

export type MetaHeroesAliases = {
	hc: "Carry";
	mid: "Mid";
	off: "Off";
	sup4: "Pos 4";
	sup5: "Pos 5";
	pos4: "Pos 4";
	pos5: "Pos 5";
};

type MetaHeroesKeys = keyof MetaHeroes;
type MetaHeroesAliasesKeys = keyof MetaHeroesAliases;
export type metaHeroesType = MetaHeroesKeys | MetaHeroesAliasesKeys;

export const heroesAliasses = {
  AntiMage: ["am", "antimage", "anti-mage"],
  Axe: ["axe"],
  Bane: ["bane"],
  Bloodseeker: ["bs", "bloodseeker", "blood seeker"],
  CrystalMaiden: ["cm", "crystal maiden", "crystal maiden"],
  DrowRanger: ["drow", "drowranger", "drow ranger"],
  Earthshaker: ["es", "earthshaker", "earth shaker"],
  Juggernaut: ["jug", "jugg", "juggernaut"],
  Mirana: ["mirana", "potm"],
  Morphling: ["morph", "morphling"],
  ShadowFiend: ["sf", "shadow fiend", "shadowfiend"],
  PhantomLancer: ["pl", "phantom lancer", "phantomlancer"],
  Puck: ["puck"],
  Pudge: ["pudge"],
  Razor: ["razor"],
  SandKing: ["sk", "sand king", "sand king"],
  StormSpirit: ["ss", "storm spirit", "stormspirit"],
  Sven: ["sven"],
  Tiny: ["tiny"],
  VengefulSpirit: ["vs", "vengeful spirit", "vengefulspirit"],
  Windranger: ["wr", "wind", "windranger"],
  Zeus: ["zeus"],
  Kunkka: ["kunkka"],
  Lina: ["lina"],
  Lion: ["lion"],
  ShadowShaman: ["ss", "shadow shaman", "sd"],
  Slardar: ["slardar"],
  Tidehunter: ["tide", "tidehunter"],
  WitchDoctor: ["wd", "witch doctor", "wd"],
  Lich: ["lich"],
  Riki: ["riki"],
  Enigma: ["enigma"],
  Tinker: ["tinker"],
  Sniper: ["sniper"],
  Necrophos: ["necrophos"],
  Warlock: ["warlock", "wl"],
  Beastmaster: ["beastmaster", "bm"],
  QueenOfPain: ["qop", "queen of pain", "queen"],
  Venomancer: ["venomancer", "veno"],
  FacelessVoid: ["fv", "faceless void", "facelessvoid"],
  WraithKing: ["wk", "wraith king", "king"],
  DeathProphet: ["dp", "death prophet"],
  PhantomAssassin: ["pa", "phantom assassin", "phantom"],
  Pugna: ["pugna"],
  TemplarAssassin: ["ta", "templar assassin", "templar"],
  Viper: ["viper"],
  Luna: ["luna"],
  DragonKnight: ["dk", "dragon knight", "dragon"],
  Dazzle: ["dazzle"],
  Clockwerk: ["cw", "clockwerk"],
  Leshrac: ["leshrac"],
  NaturesProphet: ["np", "nature's prophet", "nature"],
  Lifestealer: ["ls", "lifestealer"],
  DarkSeer: ["ds", "dark seer"],
  Clinkz: ["clinkz"],
  Omniknight: ["omniknight", "ominik"],
  Enchantress: ["enchantress", "bambi"],
  Huskar: ["huskar"],
  NightStalker: ["ns", "night stalker"],
  Broodmother: ["bm", "broodmother"],
  BountyHunter: ["bh", "bounty hunter", "bounty"],
  Weaver: ["weaver"],
  Jakiro: ["jakiro"],
  Batrider: ["batrider"],
  Chen: ["chen"],
  Spectre: ["spectre"],
  AncientApparition: ["aa", "ancient apparition", "ancient"],
  Doom: ["doom"],
  Ursa: ["ursa"],
  SpiritBreaker: ["sb", "spirit breaker", "spiritbreaker"],
  Gyrocopter: ["gyro", "gyrocopter"],
  Alchemist: ["alchemist"],
  Invoker: ["invoker"],
  Silencer: ["silencer"],
  OutworldDestroyer: ["destroyer", "outworld destroyer", "od"],
  LoneDruid: ["lone", "lone druid"],
  ChaosKnight: ["ck", "chaos knight"],
  Meepo: ["meepo"],
  TreantProtector: ["tp", "treant protector", "treant"],
  OgreMagi: ["ogre", "ogre magi"],
  Undying: ["undying"],
  Rubick: ["rubick"],
  Disruptor: ["disruptor"],
  NyxAssassin: ["nyx", "nyx assassin"],
  NagaSiren: ["naga", "naga siren"],
  KeeperOfTheLight: ["ko", "keeper of the light", "keeper" , "kotl"],
  Io: ["io"],
  Visage: ["visage"],
  Slark: ["slark"],
  Medusa: ["medusa"],
  TrollWarlord: ["tw", "troll warlord", "troll"],
  CentaurWarrunner: ["cw", "centaur", "centaur warrunner", "centaurwarrunner"],
  Magnus: ["magnus"],
  Timbersaw: ["timbersaw"],
  Bristleback: ["bristleback"],
  Tusk: ["tusk"],
  SkywrathMage: ["skywrath", "skywrath mage", "sky", "skywrathmage"],
  Abaddon: ["abaddon"],
  ElderTitan: ["et", "elder titan", "elder"],
  LegionCommander: ["lc", "legion commander", "legion"],
  Techies: ["techies"],
  EmberSpirit: ["es", "ember spirit", "ember"],
  EarthSpirit: ["es", "earth spirit", "earth"],
  Underlord: ["underlord"],
  Terrorblade: ["terrorblade", "tb"],
  Phoenix: ["phoenix"],
  Oracle: ["oracle"],
  WinterWyvern: ["ww", "winter wyvern", "winter"],
  ArcWarden: ["aw", "arc warden", "arcwarden"],
  MonkeyKing: ["mk", "monkey king", "monkey"],
  Pangolier: ["pangolier"],
  Grimstroke: ["grim", "grimstroke"],
  Mars: ["mars"],
  DarkWillow: ["dw", "dark willow", "darkwillow"],
  Medivh: ["medivh", "medivh"],
  Hoodwink: ["hoodwink", "hoodwink"],
  VoidSpirit: ["vs", "void spirit", "void"],
  Snapfire: ["snapfire", "snapfire"],
  Dawnbreaker: ["db", "dawnbreaker"],
  Marci: ["marci"],
  PrimalBeast: ["pb", "primal beast", "primal"],
  Muerta: ["muerta"],
  Lycan: ["lycan"],
  Brewmaster: ["brewmaster", "brewmaster"],
  ShadowDemon: ["sd", "shadow demon", "shadowdemon"]
}